version: '3.8'

services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: paymebot
      POSTGRES_USER: paymebot_user
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    networks:
      - paymebot_network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - paymebot_network

  web:
    build: .
    command: gunicorn --config gunicorn_config.py paymebot.wsgi:application
    volumes:
      - static_volume:/var/www/paymebot/static
      - media_volume:/app/media
    ports:
      - "8000:8000"
    environment:
      - DEBUG=False
      - SECRET_KEY=${SECRET_KEY}
      - DATABASE_URL=postgres://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
      - REDIS_URL=redis://redis:6379/1
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - EMAIL_HOST_USER=${EMAIL_HOST_USER}
      - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}
    depends_on:
      - db
      - redis
    networks:
      - paymebot_network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - static_volume:/var/www/paymebot/static
      - media_volume:/var/www/paymebot/media
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web
    networks:
      - paymebot_network

volumes:
  postgres_data:
  static_volume:
  media_volume:

networks:
  paymebot_network:
    driver: bridge